version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src/Stride.CommunityToolkit"
    schedule:
      interval: daily
    allow:
      - dependency-name: "Stride.*"    
    groups:
      stride:
        patterns:
          - "Stride.*"
  - package-ecosystem: nuget
    directory: "/src/Stride.CommunityToolkit.Bepu"
    schedule:
      interval: daily
    allow:
      - dependency-name: "Stride.*"      
    groups:
      stride:
        patterns:
          - "Stride.*"
  - package-ecosystem: nuget
    directory: "/src/Stride.CommunityToolkit.DebugShapes"
    schedule:
      interval: daily
    allow:
      - dependency-name: "Stride.*"      
    groups:
      stride:
        patterns:
          - "Stride.*"
  - package-ecosystem: nuget
    directory: "/src/Stride.CommunityToolkit.ImGui"
    schedule:
      interval: daily
    allow:
      - dependency-name: "Stride.*"      
    groups:
      stride:
        patterns:
          - "Stride.*"
  - package-ecosystem: nuget
    directory: "/src/Stride.CommunityToolkit.Skyboxes"
    schedule:
      interval: daily
    allow:
      - dependency-name: "Stride.*"      
    groups:
      stride:
        patterns:
          - "Stride.*"
  - package-ecosystem: nuget
    directory: "/src/Stride.CommunityToolkit.Windows"
    schedule:
      interval: daily
    allow:
      - dependency-name: "Stride.*"      
    groups:
      stride:
        patterns:
          - "Stride.*"
