name: Update Stride Packages

on:
  workflow_dispatch:      # Allow manual triggering

jobs:
  update-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust version as needed

      - name: Update Stride packages
        id: update
        run: |
          # Find all projects
          projects=($(find . -name "*.csproj"))
          
          # Track whether any updates were made
          updates_made=false
          
          # Store update details for PR
          echo "UPDATES_LIST<<EOF" >> $GITHUB_ENV
          
          for project in "${projects[@]}"; do
            echo "Checking $project for Stride package updates..."
            
            # List current Stride packages and versions
            current_packages=$(dotnet list $project package | grep "Stride\.")
            
            if [[ ! -z "$current_packages" ]]; then
              # Update all Stride packages
              dotnet add $project package Stride.* --update-references
              
              # Get updated packages and versions
              updated_packages=$(dotnet list $project package | grep "Stride\.")
              
              # Compare to see if any packages were updated
              if [[ "$current_packages" != "$updated_packages" ]]; then
                updates_made=true
                echo "Updated packages in $project:" >> $GITHUB_ENV
                echo "$updated_packages" >> $GITHUB_ENV
                echo "" >> $GITHUB_ENV
              fi
            fi
          done
          
          echo "EOF" >> $GITHUB_ENV
          
          # Set output indicating if updates were found
          echo "updates_found=$updates_made" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.update.outputs.updates_found == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "build: update Stride packages"
          title: "Update Stride NuGet packages"
          body: |
            # Stride Package Updates
            
            This PR updates the following Stride packages:
            
            ```
            ${{ env.UPDATES_LIST }}
            ```
            
            Auto-generated by the Update Stride Packages workflow.
          branch: stride-package-updates
          base: main  # Change to your default branch if different
